apiVersion: v1
kind: Service
metadata:
  name: trendit-service
  namespace: default
  labels:
    app: trendit-demo
spec:
  selector:
    app: trendit-demo
  type: NodePort
  ports:
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300
  sessionAffinity: ClientIP
